### ISSUE TITLE
Taille de typo responsive

### ISSUE THREAD

**Issue by loup-brun** [loup-brun/desorde.loupbrun.ca#26]
exemple tiré d'Abrüpt:

```css
body {
  font-size: calc(20px + 6*(100vw - 300px)/980);
}
```
